# Site settings 配置站点
title: '虚无与质感'
description: '无趣的生活里发现有限的乐趣'
keywords: '电影, 摄影, 旅行'
url: 'https://reinaz.github.io' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  关于博主: '/about.html'
  友情链接: '/friendLink.html'

# 博主
author: true
name: 'ReinaZ'
NickName: 'ReinaZ'
webtitle: 'ReinaZ'
bio: '电影从业者'
about: true
aboutyou: '一个18岁少女。'
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  weibo: 'https://weibo.com/rong1218?is_hot=1'
  mail: 'mailto:kumiko1218@163.com'

# 分页
paginate: 10
paginatepath: ['page:num']

# since
footer:
  since: 2018

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
friends:
  jekyll: 'https://jekyllrb.com/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC80MTgxMS8xODM1Nw==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['wechat', 'qq', 'weibo', 'douban', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: false
baidu-url: '7d044e486aa94a8d389b75fbb970da8e'
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: true
google-ID: 'UA-131386595-1'

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)

excerpt_separator: <!--excerpt-->  #这里可以定义自己的摘要分割符
